// warinternal 24 November 2016 at 04:15
global.RAMPART_UPKEEP =
  RAMPART_DECAY_AMOUNT / REPAIR_POWER / RAMPART_DECAY_TIME;
global.ROAD_UPKEEP = ROAD_DECAY_AMOUNT / REPAIR_POWER / ROAD_DECAY_TIME;
global.CONTAINER_UPKEEP =
  CONTAINER_DECAY / REPAIR_POWER / CONTAINER_DECAY_TIME_OWNED;
global.REMOTE_CONTAINER_UPKEEP =
  CONTAINER_DECAY / REPAIR_POWER / CONTAINER_DECAY_TIME;
